### ISSUE TITLE
ArtyZ7_20Master.xdc: incorrect create_clock period constraint on clk (H16)?

### ISSUE THREAD

**Issue by grayresearch** [Digilent/Arty-Z7#1]
In Resources/XDC/*.xdc, the constraint on the external clock input from the RealTek ethernet PHY into the PL on pin H16 is constrained to be 10 ns / 100 MHz, whereas it should be 8 ns / 125 MHz:

Is:
#set_property -dict { PACKAGE_PIN H16    IOSTANDARD LVCMOS33 } [get_ports { clk }]; #IO_L13P_T2_MRCC_35 Sch=SYSCLK
#create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { clk }];#set

should be:
#create_clock -add -name sys_clk_pin -period 8.00 -waveform {0 4} [get_ports { clk }];#set

**Comment by evancox10** [comment]
I agree with you, I checked the datasheet of the REALTEK part supplying the clock, and it is 125 MHz.
