### ISSUE TITLE
invalid path during build

### ISSUE THREAD

**Issue by lzto** [Digilent/Arty-Z7#1]
Hi,
I have a question about the project build path issue.
I imported the zip file into vitis, when I hit build button, I see the following error. do you happen to know why?
Thanks!

```
make[1]: *** No rule to make target 'E:/UpgradeProjects/Arty-Z7/sw/src/Arty-Z7-20-OOB/src/lscript.ld', needed by 'Arty-Z7-20-OOB.elf'.  Stop.
make: *** [makefile:40: all] Error 2
```

**Comment by lzto** [comment]
after some digging, I find out **ldscript.ld** need to be regenerated 
I regenerated it using menu Xilinx->Generate Linker script -- after that it worked

**Comment by artvvb** [comment]
Thanks for pointing this out. I've added instructions on how to fix the linker script import to the wiki documentation for the demo: https://digilent.com/reference/programmable-logic/arty-z7/demos/oob (Using the Latest Release / Apply Fix for Linker Script Bug). Recreating the linker script is likely fine in this case, but care should be taken as it may have been modified from the default.
